[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
weather-tgbot = { path = ".." }
teloxide = "0.15.0"
teloxide_tests = "0.3.0"
tokio = { version = "1", features = ["full"] } 